apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: swagger-spring-boot-app
  description: A Spring Boot application with Swagger integration.
  owner: team-lisa
spec:
  type: service
  lifecycle: production
  owner: team-lisa
  providesApis:
    - api: swagger-spring-boot-app-api
  implementsApis:
    - api: swagger-spring-boot-app-api
  definition:
    type: openapi
    content:
      url: http://localhost:8080/v2/api-docs
  techdocs:
    path: ./docs